### ISSUE TITLE
change usage if dict.iteritems() to dict.items() for Python 3 compatibility.

### ISSUE THREAD

**Issue by DrumFrog** [mjrao/pyxml2dict#2]
In Python 2, dict.items() returned a list of dictionary items, while dict.iteritems() returned an iterator.
In Python 3, dict.items() now returns an iterator and dict.iteritems() does not exist anymore, so using XML2Dict results in an error in Python 3 environments.

Therefore, I'd propose to change the calls of iteritems() directly to items().

I'll open an according pull request shortly.

**Comment by ai0376** [comment]
LGTM
