### ISSUE TITLE
release update to pypi.org

### ISSUE THREAD

**Issue by DrumFrog** [mjrao/pyxml2dict#4]
After 2 pull requests merged, I think the updated package (v1.0.3?) should be released on official pypi.

Background:
- version in setup.py after merging PR #1 is 1.0.2
- version on https://pypi.org/project/pyxml2dict/ is 1.0.1
- installing using ``pip install py2xml`` results in 1.0.1 being installed

**Comment by ai0376** [comment]
release update.
